COMM_STRUCT = {}

COMM_STRUCT_ID = {
    CS_EVENT_DESTROY_SELF = 1,
    CS_FOLLOW_DESTROY = 2,
}

local CS = COMM_STRUCT

CS[COMM_STRUCT_ID.CS_EVENT_DESTROY_SELF] = {
    id = "CS_EVENT_DESTROY_SELF",
    bigtype = COMP_TYPE.EVENT_DESTROY,
    listen = {
        {OBJ_EVENT.DO_DESTROY_SELF}
    },
}

CS[COMM_STRUCT_ID.CS_FOLLOW_DESTROY] = {
    id = "CS_FOLLOW_DESTROY",
    bigtype = COMP_TYPE.FOLLOW_DESTROY,
}